### ISSUE TITLE
Add example project

### ISSUE THREAD

**Issue by kylegalbraith** [slalompdx/terraform-aws-codecommit-cicd#1]
Using the module and showing the configuration needed for `buildspec_test.yml` to feed the artifacts into the package build.

```yaml
artifacts:
  files:
    - '**/*'
```
